routes/admin.php
<?php

use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\CategoriesController;
use Illuminate\Support\Facades\Route;


//Route prefix để nhóm các route có admin/ đằng trước
//dùng middleware auth khi chưa đăng nhập sẽ tự động redirect đến trang login có thể sửa redirect đến
//trang đích khác trong Middlware/Authentication
//dùng ->as('admin') để thêm admin. trước route
Route::get('login',[LoginController::class,'showFormLogin'])->name('auth.login');
Route::post('login',[LoginController::class,'login'])->name('postLogin');
Route::post('logout',[LoginController::class,'logout'])->name('auth.logout');
Route::prefix('admin')
    ->as('admin.')
    ->middleware(['auth','check_admin'])
    ->group(function (){
        Route::get('/',function ()
        {
            $title = 'SB Admin 2 - Dashboard';
            return view('admin.dashboard',compact('title'));
        })->name('dashboard');
        Route::resource('users',UserController::class);
        Route::get('profile/{id}',[ProfileController::class,'index'])->name('profile.edit');
        Route::post('profile/{id}',[ProfileController::class,'update'])->name('profile.update');
        Route::resource('category', CategoriesController::class);
    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

include(base_path('routes/admin.php'));
include(base_path('routes/website.php'));

Route::fallback( function (){
   abort(404);
});

app/Http/Controllers/Admin/ProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProfileUpdateRequest;
use App\Models\User;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;

class ProfileController extends Controller
{
    public function index(string $id)
    {
        $data = User::query()->findOrFail($id);
        return view('admin.profile.index', compact('data'));
    }

    public function update(ProfileUpdateRequest $request, string $id)
    {
        //lấy ra đối tượng user có id = id trên url
        $model = User::query()->findOrFail($id);
        try {
            //except bỏ qua trường avatar
            $model->fill($request->except('avatar'));
            //lấy ra file avatar cũ
            $oldAvt = $model->avatar;
            //kiểm tra dữ liệu gửi lên có tồn tại trường avatar hay không
            if ($request->hasFile('avatar')) {
                //nếu có thì thực hiện update file và xóa file cũ
                $model->avatar = upload_file(OBJECT_USER, $request->file('avatar'));
                $model->save();
                //xóa file cũ
                delete_file($oldAvt);
            } else {
                //nếu không có thì cập nhật những dữ liệu có thay đổi và bỏ qua cập nhật trường avt
                $model->save();
            }
            return back()->with('status',Response::HTTP_OK)
                ->with('msg','Thao tác thành công');
        } catch (\Exception $exception) {
            Log::error('Exception', [$exception]);
            return back()->with('status',Response::HTTP_BAD_REQUEST)
                ->with('msg','Thao tác thất bại');
        }
    }
}

resources/views/admin/profile/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container-fluid">
        <div class="card shadow mb-4 pt-2 pb-5">
            <form action="{{route('admin.profile.update',$data)}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="col-md-6">
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{$data->name}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <label for="avatar" class="form-label">Avatar</label>
                    <div class="mb-3">
                        <img src="{{asset($data->avatar)}}" width="150px" height="150px" style="margin-bottom: 10px">
                        <input type="file" class="form-control" id="avatar" name="avatar">
                    </div>
                </div>
                <div class="col-md-6">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
@endsection