routes/admin.php
<?php

use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Admin\CategoriesController;
use Illuminate\Support\Facades\Route;


//Route prefix để nhóm các route có admin/ đằng trước
//dùng middleware auth khi chưa đăng nhập sẽ tự động redirect đến trang login có thể sửa redirect đến
//trang đích khác trong Middlware/Authentication
//dùng ->as('admin') để thêm admin. trước route
Route::get('login',[LoginController::class,'showFormLogin'])->name('auth.login');
Route::post('login',[LoginController::class,'login'])->name('postLogin');
Route::post('logout',[LoginController::class,'logout'])->name('auth.logout');
Route::prefix('admin')
    ->as('admin.')
    ->middleware(['auth','check_admin'])
    ->group(function (){
        Route::get('/',function ()
        {
            $title = 'SB Admin 2 - Dashboard';
            return view('admin.dashboard',compact('title'));
        })->name('dashboard');
        Route::resource('users',UserController::class);
        Route::get('profile/{id}',[ProfileController::class,'index'])->name('profile.edit');
        Route::post('profile/{id}',[ProfileController::class,'update'])->name('profile.update');
        Route::resource('category', CategoriesController::class);
    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

include(base_path('routes/admin.php'));
include(base_path('routes/website.php'));

Route::fallback( function (){
   abort(404);
});

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoriesUpdateRequest;
use App\Http\Requests\StoreCategoriesRequest;
use App\Models\Categories;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = Categories::query()->orderByDesc('id')->get();
        $title = "Danh sách danh mục";
        return view(OBJECT_ADMIN . DOT . OBJECT_CATEGORY . DOT . __FUNCTION__,
            compact('data','title'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $title = "Thêm mới danh mục";
        return view(OBJECT_ADMIN . DOT . OBJECT_CATEGORY . DOT . __FUNCTION__,compact('title'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoriesRequest $request)
    {
        try {
            $model = new Categories();
            $model->fill($request->all());
            $model->save();

            return redirect()->route('admin.category.index')->with('status',Response::HTTP_OK)
                ->with('msg','Thêm mới thành công!');
        }catch (\Exception $exception){
            Log::error('Exception',[$exception]);

            return back()->with('status',Response::HTTP_BAD_REQUEST)
                ->with('msg','Thao tác thất bại!');
        }

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $title = "Sửa danh mục";
        $model = Categories::query()->findOrFail($id);
        return view(OBJECT_ADMIN . DOT . OBJECT_CATEGORY . DOT . __FUNCTION__,
            compact('title','model'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(CategoriesUpdateRequest $request, string $id)
    {
        try {
            $model = Categories::query()->findOrFail($id);
            $model->fill($request->all());
            $model->save();

            return back()->with('status',Response::HTTP_OK)->with('msg','Cập nhật thành công!');
        }catch (\Exception $exception){
            Log::error('Exception',[$exception]);
            return back()->with('status',Response::HTTP_BAD_REQUEST)->with('msg','Thao tác thất bại!');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $categories = Categories::query()->findOrFail($id);
        $categories->delete();
        return back()->with('status',Response::HTTP_OK)->with('msg','Xóa thành công!');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.master')

@section('title')
    {{$title}}
@endsection
@section('content')
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Thêm mới danh mục</h1>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Form</h6>
            </div>
            <div class="card-body">
                <form method="post" action="{{route('admin.category.store')}}">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="name" class="form-label">Tên danh mục</label>
                                <input type="text" class="form-control" id="name" name="name">
                            </div>
                            <div class="mb-3">
                                <label for="describe" class="form-label">Mô tả</label>
                                <input type="text" class="form-control" id="describe" name="describe">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Thêm mới</button>
                </form>
            </div>
        </div>

    </div>
@endsection

@push('styles')

@endpush
@push('script')

@endpush

resources/views/admin/categories/edit.blade.php
@extends('layouts.master')

@section('title')
    {{$title}}
@endsection
@section('content')
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Sửa danh mục</h1>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Form</h6>
            </div>
            <div class="card-body">
                <form method="post" action="{{route('admin.category.update',$model)}}">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="name" class="form-label">Tên danh mục</label>
                                <input type="text" class="form-control" id="name" name="name"
                                       value="{{$model->name}}">
                            </div>
                            <div class="mb-3">
                                <label for="describe" class="form-label">Mô tả</label>
                                <input type="text" class="form-control" id="describe" name="describe"
                                       value="{{$model->describe}}">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                </form>
            </div>
        </div>

    </div>
@endsection

@push('styles')

@endpush
@push('script')

@endpush

resources/views/admin/categories/index.blade.php
@extends('layouts.master')

@section('title')
    {{$title}}
@endsection
@section('content')
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Danh sách danh mục</h1>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">List</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tên</th>
                            <th>Mô tả</th>
                            <th>Thao tác</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($data as $item)
                            <tr>
                                <td>{{$item->id}}</td>
                                <td>{{$item->name}}</td>
                                <td>{{$item->describe}}</td>
                                <td>
                                    <a class="btn btn-primary" href="{{route('admin.category.edit',$item)}}">Edit</a>
                                    <button class="btn btn-danger"
                                            onclick="document.getElementById('item-{{$item->id}}').submit();">Delete
                                    </button>

                                    <form action="{{route('admin.category.destroy',$item)}}" id="item-{{$item->id}}"
                                          method="post">
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
@endsection

@push('styles')
    <link href="{{asset('be/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endpush
@push('script')
    <!-- Page level plugins -->
    <script src="{{asset('be/vendor/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('be/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

    <!-- Page level custom scripts -->
    <script src="{{asset('be/js/demo/datatables-demo.js')}}"></script>
@endpush